version: '3.8'

services:

  # ---------- Traefik ----------
  traefik:
    image: traefik:2.10
    container_name: traefik
    command:
      - --api.insecure=false # PASSÉ À FALSE POUR LA PROD
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    restart: always

  # ---------- Redis ----------
  redis:
    image: redis:7.2.4-alpine # Version plus précise
    container_name: redis
    networks:
      - traefik-public
    restart: always

  # ---------- PostgreSQL Airflow ----------
  postgres-airflow:
    image: postgres:16.1
    container_name: postgres-airflow
    networks:
      - traefik-public
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data
      - ${POSTGRE_INIT}:/docker-entrypoint-initdb.d
    restart: always

  # ---------- PostgreSQL Exporter ----------
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0 # FIXÉE À UNE VERSION STABLE
    container_name: postgres-exporter
    networks:
      - traefik-public
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"
    volumes:
      - ${POSTGRES_EXPORTER_PATH}:/postgres_exporter.yml
    depends_on:
      - postgres-airflow
    restart: always

  # ---------- MinIO ----------

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z # FIXÉE À UNE VERSION STABLE
    container_name: minio
    networks:
      - traefik-public
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:9090
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio:/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.itceq.tn`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  minio-create-buckets:
    image: minio/mc:RELEASE.2024-11-05T11-29-45Z # FIXÉE À UNE VERSION STABLE
    container_name: minio-create-buckets
    networks:
      - traefik-public
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set myminio http://minio:${MINIO_API_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb -p myminio/01-raw;
        mc mb -p myminio/02-transformed;
        mc mb -p myminio/03-refined;
        mc mb -p myminio/90-sandbox;
        mc ls myminio;
      "
    restart: "no"



  # ---------- Spark ----------
  spark-master:
    build: ./spark
    container_name: spark-master
    networks:
      - traefik-public
    user: root
    environment:
      USER: root
      SPARK_USER: root
      HADOOP_USER_NAME: root
      SPARK_METRICS_CONF: "/opt/spark/conf/metrics.properties"
      SPARK_MASTER_OPTS: "-Dspark.metrics.conf=/opt/spark/conf/metrics.properties -DmetricsServlet.port=8090"
      SPARK_SUBMIT_OPTS: >-
        -Dspark.eventLog.enabled=true
        -Dspark.eventLog.dir=file:///opt/spark/events
    ports:
      - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
      - "${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077
    volumes:
      - ${MINIO_RAW_PATH}:/data/raw
      - ${MINIO_TRANSFORMED_PATH}:/data/transformed
      - ${MINIO_REFINED_PATH}:/data/refined
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${SPARK_EVENT_PATH}:/opt/spark/events
      - ${SPARK_PROPERTIES_PATH}:/opt/spark/conf/metrics.properties
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spark.rule=Host(`spark.itceq.tn`)"
      - "traefik.http.routers.spark.entrypoints=web"
      - "traefik.http.services.spark.loadbalancer.server.port=8080"

  spark-worker:
    build: ./spark
    container_name: spark-worker
    networks:
      - traefik-public
    depends_on:
      - spark-master
    environment:
      USER: root
      SPARK_USER: root
      HADOOP_USER_NAME: root
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_METRICS_CONF: "/opt/spark/conf/metrics.properties"
      SPARK_WORKER_OPTS: "-Dspark.metrics.conf=/opt/spark/conf/metrics.properties -DmetricsServlet.port=8091"
      SPARK_SUBMIT_OPTS: >-
        -Dspark.eventLog.enabled=true
        -Dspark.eventLog.dir=file:///opt/spark/events
    ports:
      - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ${MINIO_RAW_PATH}:/data/raw
      - ${MINIO_TRANSFORMED_PATH}:/data/transformed
      - ${MINIO_REFINED_PATH}:/data/refined
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${SPARK_EVENT_PATH}:/opt/spark/events
      - ${SPARK_PROPERTIES_PATH}:/opt/spark/conf/metrics.properties
    restart: always

  spark-history-server:
    build: ./spark
    container_name: spark-history-server
    networks:
      - traefik-public
    environment:
      SPARK_HISTORY_OPTS: >-
        -Dspark.history.fs.logDirectory=file:///opt/spark/events
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
    volumes:
      - ${SPARK_EVENT_PATH}:/opt/spark/events
    ports:
      - "18080:18080"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spark-history.rule=Host(`spark-history.itceq.tn`)"
      - "traefik.http.routers.spark-history.entrypoints=web"

  spark-exporter:
    build: ./spark/spark-exporter
    container_name: spark-exporter
    networks:
      - traefik-public
    depends_on:
      - spark-master
    ports:
      - "${SPARK_EXPORTER_PORT}:${SPARK_EXPORTER_PORT}"
    restart: always

  # ------------------------
  # Prometheus
  # ------------------------
  prometheus:
    image: prom/prometheus:v2.45.0 # Version LTS FIXÉE
    networks:
      - traefik-public
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'  # 1 an de rétention (au lieu de 90j)
      - '--storage.tsdb.retention.size=100GB'  # 100GB max (au lieu de 50GB)
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.itceq.tn`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"


  # ---------- Airflow ----------
  airflow-init:
    build: ./airflow
    container_name: airflow-init
    networks:
      - traefik-public
    depends_on:
      - postgres-airflow
      - redis
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}
      OPENLINEAGE_URL: ${MARQUEZ_URL}
      OPENLINEAGE_NAMESPACE: itceq_prod
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    env_file:
        - .env
    volumes:
      - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${AIRFLOW_PLUGINS_PATH}:/opt/airflow/plugins
      - ./airflow/init_connections.py:/opt/airflow/init_connections.py
 
 
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create \
          --username ${AIRFLOW_ADMIN_USER} \
          --password ${AIRFLOW_ADMIN_PASSWORD} \
          --firstname Admin \
          --lastname Admin \
          --email admin@example.org \
          --role Admin || true &&
        python /opt/airflow/init_connections.py
      "


  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    networks:
      - traefik-public
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}
      OPENLINEAGE_URL: ${MARQUEZ_URL}
      OPENLINEAGE_NAMESPACE: itceq_prod
      
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    env_file:
        - .env
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:8080"
    volumes:
      - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${DATA_PATH}:/opt/airflow/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airflow.rule=Host(`airflow.itceq.tn`)"
      - "traefik.http.routers.airflow.entrypoints=web"
      - "traefik.http.services.airflow.loadbalancer.server.port=8080"
    command: airflow webserver


  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    networks:
      - traefik-public
    depends_on:
      - airflow-init
      - redis
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}
      OPENLINEAGE_URL: ${MARQUEZ_URL}
      OPENLINEAGE_NAMESPACE: itceq_prod
      
    env_file:
        - .env
    volumes:
      - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${DATA_PATH}:/opt/airflow/data
    command: airflow scheduler
    restart: always

 # ------------------------
  # Airflow Triggerer
  # ------------------------
  airflow-triggerer:
    build: ./airflow
    depends_on:
      - postgres-airflow
      - redis
    networks:
      - traefik-public
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__WEBSERVER__SESSION_BACKEND: securecookie
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      AIRFLOW__CORE__HIDE_SENSITIVE_VAR_CONN_FIELDS: 'False'
      OPENLINEAGE_URL: ${MARQUEZ_URL}
      OPENLINEAGE_NAMESPACE: itceq_prod
    env_file:
      - .env
    volumes:
      - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs
      - ${MINIO_RAW_PATH}:/data/raw
      - ${MINIO_TRANSFORMED_PATH}:/data/transformed
      - ${DATA_PATH}:/opt/airflow/data
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
    command: triggerer
    restart: always

  # ------------------------
  # Airflow Exporter
  # ------------------------
  airflow-exporter:
      build: ./airflow/airflow-exporter
      networks:
        - traefik-public
      environment:
        EXPORTER_PORT: 9112
        AIRFLOW_WEBSERVER: "http://airflow-webserver:8080/api/v1"
        AIRFLOW_USER: "${AIRFLOW_ADMIN_USER}"
        AIRFLOW_PASSWORD: "${AIRFLOW_ADMIN_PASSWORD}"
        AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
        LOKI_URL: "${LOKI_URL}"
        LOGS_PATH: "${AIRFLOW_CONTAINER_LOGS}"
        METRICS_TIME_WINDOW_DAYS: "30"  # Période de filtrage des métriques (peut être modifiée)
      env_file:
        - .env
      ports:
        - "${AIRFLOW_EXPORTER_PORT}:${AIRFLOW_EXPORTER_PORT}"
      volumes:
        - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs:ro
        - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags:ro
      depends_on:
        - airflow-webserver
        - loki
      restart: always

  airflow-worker:
    build: ./airflow
    container_name: airflow-worker
    networks:
      - traefik-public
    depends_on:
      - airflow-init
      - redis
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-airflow:5432/${POSTGRES_DB}
      OPENLINEAGE_URL: ${MARQUEZ_URL}
      OPENLINEAGE_NAMESPACE: itceq_prod
      
    env_file:
        - .env
    volumes:
      - ${AIRFLOW_DAGS_PATH}:/opt/airflow/dags
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs
      - ${SPARK_JOBS_PATH}:/opt/spark/jobs
      - ${AIRFLOW_PLUGINS_PATH}:/opt/airflow/plugins
      - ${DATA_PATH}:/opt/airflow/data
    command: airflow celery worker
    restart: always

  # ---------- Marquez ----------
  marquez-postgres:
    image: postgres:16-alpine
    container_name: marquez-postgres
    networks: [traefik-public]
    environment:
      POSTGRES_DB: ${MARQUEZ_POSTGRES_DB}
      POSTGRES_USER: ${MARQUEZ_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MARQUEZ_POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MARQUEZ_POSTGRES_USER} -d ${MARQUEZ_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./marquez_pg_data:/var/lib/postgresql/data

  marquez:
    image: marquezproject/marquez:0.49.0
    container_name: marquez
    networks: [traefik-public]
    depends_on:
      - marquez-postgres
    environment:
      # Indique à l'appli où trouver le fichier qu'on vient de créer
      MARQUEZ_CONFIG: /etc/marquez/marquez.yml
      # Vos variables de connexion
      MARQUEZ_DB_URL: ${MARQUEZ_DB_URL}
      MARQUEZ_DB_USER: ${MARQUEZ_DB_USER}
      MARQUEZ_DB_PASSWORD: ${MARQUEZ_DB_PASSWORD}
      JAVA_OPTS: >
       -javaagent:/opt/jmx/jmx_prometheus_javaagent.jar=9404:/opt/jmx/jmx-config.yml
    volumes:
    - ./jmx/jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx/jmx_prometheus_javaagent.jar
    - ./jmx/jmx-config.yml:/opt/jmx/jmx-config.yml
    - ./marquez.yml:/etc/marquez/marquez.yml:ro

    ports:
      - "${MARQUEZ_HTTP_PORT}:${MARQUEZ_HTTP_PORT}"
      - "${MARQUEZ_ADMIN_PORT}:${MARQUEZ_ADMIN_PORT}"
      - "9404:9404"

    restart: always

  #   # JMX Exporter pour Marquez
  # marquez-jmx-exporter:
  #   image: bitnami/jmx-exporter:latest
  #   container_name: marquez-jmx-exporter
  #   networks: [traefik-public]
  #   depends_on:
  #     - marquez
  #   command:
  #     - "9404"
  #     - "/etc/jmx-exporter/config.yml"
  #   volumes:
  #     - ./jmx-exporter-config.yml:/etc/jmx-exporter/config.yml:ro
  #   ports:
  #     - "9504:9404"
  #   restart: always


  sql-exporter:
    image: burningalchemist/sql_exporter:latest
    container_name: sql-exporter
    environment:
      - CONFIG=/config/sql_exporter.yml
    volumes:
      - ./sql_exporter.yml:/config/sql_exporter.yml
    networks:
      - traefik-public
    ports:
      - "9399:9399"
 
  marquez-web:
    image: marquezproject/marquez-web:0.41.0
    container_name: marquez-web
    networks: [traefik-public]
    depends_on:
      - marquez
    environment:
      - MARQUEZ_URL=${MARQUEZ_URL}
    ports:
      - "3050:3000"
 
  marquez-proxy:
    image: nginx:alpine
    container_name: marquez-proxy
    networks: [traefik-public]
    depends_on:
      - marquez
      - marquez-web
    ports:
      - "3002:80"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marquez-ui.rule=Host(`marquez.itceq.tn`)"
      - "traefik.http.routers.marquez-ui.entrypoints=web"
      - "traefik.http.services.marquez-ui.loadbalancer.server.port=80"


  # ------------------------
  # Grafana
  # ------------------------
  grafana:
    image: grafana/grafana:10.4.3
    networks:
      - traefik-public
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ${GRAFANA_PROVISIONING_PATH}:/etc/grafana/provisioning
      - ${GRAFANA_DASHBOARDS_PATH}:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.itceq.tn`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # ------------------------
  # Metabase
  # ------------------------
    # 1. METABASE APP (Port 3021)
  metabase:
    build:
      context: ./metabase/build
      dockerfile: Dockerfile
    container_name: metabase_app
    networks:
      - traefik-public
    restart: unless-stopped
    ports:
      - "${METABASE_PORT}:3000"
      - "${METABASE_EXPORTER_PORT}:${METABASE_EXPORTER_PORT}"
    env_file:
      - ${METABASE_ENV_FILE}
    depends_on:
      metabase_db_internal:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.rule=Host(`metabase.itceq.tn`)"
      - "traefik.http.routers.metabase.entrypoints=web"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
    environment:
      - MB_PROMETHEUS_SERVER_PORT=9191
 
  # 2. INTERNAL METADATA DB
  metabase_db_internal:
    image: postgres:16.1
    networks:
      - traefik-public
    container_name: metabase_db_internal
    environment:
      POSTGRES_DB: ${METABASE_POSTGRES_DB}
      POSTGRES_USER: ${METABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${METABASE_POSTGRES_PASSWORD}
    volumes:
      - mb_internal_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Donne 10s à Postgres pour créer la DB avant de tester

  # ------------------------
  # Metabase Exporter
  # ------------------------
  metabase-exporter:
    build: ./metabase/metabase-exporter
    container_name: metabase-exporter
    networks:
      - traefik-public
    environment:
      METABASE_URL: "${METABASE_URL}"
      METABASE_USERNAME: "${METABASE_USERNAME}"
      METABASE_PASSWORD: "${METABASE_PASSWORD}"
      EXPORTER_PORT: "${METABASE_EXPORTER_PORT}"
      SCRAPE_INTERVAL: "${METABASE_SCRAPE_INTERVAL}"
    ports:
      - "9102:${METABASE_EXPORTER_PORT}"
    depends_on:
      - metabase
    restart: always
 
  # 3. ZERO-TOUCH DEPLOYER (The Magic)
  metabase_deployer:
    image: python:3.9-slim
    networks:
      - traefik-public
    container_name: metabase_deployer
    depends_on:
      - metabase
    volumes:
      - ${METABASE_SCRIPTS_PATH}:/scripts
      - ${METABASE_SAVED_STATES_PATH}:/saved_states # Mounts the JSONs
    working_dir: /scripts
    env_file:
      - ${METABASE_ENV_FILE}
    # Install libs -> Run Setup -> Run Import -> Exit
    command: >
      sh -c "pip install requests metabase-api && python deploy_solution.py"
 
 


  # ------------------------
  # pgAdmin
  # ------------------------
  pgadmin:
    image: dpage/pgadmin4:8.2 # FIXÉE À UNE VERSION STABLE
    networks:
      - traefik-public
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${PGADMIN_SERVERS_PATH}:/pgadmin4/servers.json
    depends_on:
      - postgres-airflow
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.itceq.tn`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"


  # ------------------------
  # Loki (pour logs Airflow)
  # ------------------------
  loki:
    image: grafana/loki:2.9.4

    networks:
      - traefik-public
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${LOKI_DATA_INDEX_PATH}:/loki/index
      - ${LOKI_DATA_CHUNKS_PATH}:/loki/chunks
      - ${LOKI_DATA_WAL_PATH}:/loki/wal
      - ${LOKI_CONFIG_PATH}:/etc/loki/local-config.yaml
      
    restart: always
 
  # ------------------------
  # Promtail (agent qui envoie les logs à Loki)
  # ------------------------
  promtail:
    image: grafana/promtail:2.9.4
    networks:
      - traefik-public
    volumes:
      - ${PROMTAIL_CONFIG_PATH}:/etc/promtail/config.yaml:ro
      - ${AIRFLOW_LOGS_PATH}:/opt/airflow/logs:ro
      # Pas de volume persistant pour positions - force la relecture à chaque restart
    ports:
      - "${PROMTAIL_PORT}:${PROMTAIL_PORT}"
    command: -config.file=/etc/promtail/config.yaml
    restart: always



# ------------------------ Volumes ------------------------
volumes:
  prometheus_data:
  mb_internal_data:
  marquez_pg_data:
  minio-data:

# ------------------------ Networks ------------------------
networks:
  traefik-public:
    driver: bridge