---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "java.lang:*"
  - "java.nio:*"
  - "metrics:*"
  - "Hadoop:*"
blacklistObjectNames: []
rules:
  - pattern: 'metrics<name=(\w+)\.(\w+)\.(\w+)\.(.+)><>Value'
    name: spark_$2_$3_$4
    labels:
      app: "$1"
  - pattern: 'metrics<name=(\w+)\.(\w+)\.(.+)><>Value'
    name: spark_$2_$3
    labels:
      app: "$1"
  - pattern: "java.lang<type=(.+), name=(.+)><(.+)>(\w+)"
    name: java_lang_$1_$3_$4
    labels:
      name: "$2"
  - pattern: "java.lang<type=(.+), name=(.+)><>(\w+)"
    name: java_lang_$1_$3
    labels:
      name: "$2"
  - pattern: "java.lang<type=(.*)><(.+)>(\w+)"
    name: java_lang_$1_$2_$3