# ===============================
# Prometheus Sink (Pull model)
# ===============================
# Active le servlet pour que Prometheus puisse scraper les métriques
*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus

# ===============================
# Sources de métriques
# ===============================
# Active la collecte des métriques JVM (GC, Memory, Threads)
master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource