# ===============================
# S3A / MinIO Committer (CRUCIAL)
# ===============================
spark.hadoop.fs.s3a.committer.name=directory
spark.hadoop.fs.s3a.committer.staging.conflict-mode=replace
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version=2
spark.hadoop.fs.s3a.committer.staging.tmp.path=/opt/spark/work/s3a-staging
spark.hadoop.fs.s3a.committer.staging.abort.pending.uploads=true

# ===============================
# MinIO S3A (exemple)
# ===============================
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
