# ===============================
# S3A / MinIO Configuration
# ===============================
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

# ===============================
# S3A Committer (OPTIMISATION)
# ===============================
# "directory" stocke en local avant upload (fiable mais lent et utilise le disque)
# "magic" écrit directement sur S3 (plus rapide, 0 disque local requis)
# Recommandé pour MinIO récent : magic
spark.hadoop.fs.s3a.committer.name=magic
spark.hadoop.fs.s3a.committer.magic.enabled=true

# Si vous gardez "directory", assurez-vous que /opt/spark/work a assez d'espace disque
# spark.hadoop.fs.s3a.committer.name=directory
# spark.hadoop.fs.s3a.committer.staging.tmp.path=/opt/spark/work/s3a-staging

# Gestion des conflits (Important pour votre mode("overwrite"))
spark.hadoop.fs.s3a.committer.staging.conflict-mode=replace

# ===============================
# OpenLineage (Déplacé ici !)
# ===============================
spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.transport.type=http
spark.openlineage.transport.url=http://marquez:5000/api/v1/lineage
spark.openlineage.namespace=spark-prod-ins

# ===============================
# Performance & Tuning Générique
# ===============================
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.sql.hive.convertMetastoreParquet=false