# =======================================
# METABASE ENV CONFIG
# =======================================

# -----------------------------
# Metabase DEV credentials
# -----------------------------

DEV_METABASE_CONTAINER="metabase"
DEV_POSTGRES_CONTAINER="data_platform-postgres-airflow-1"
DEV_DB_NAME="metabase_db"
DEV_DB_USER="airflow"
DEV_DB_PASS="airflow"
DEV_DB_HOST="postgres-airflow"
DEV_DB_PORT="5432"

# -----------------------------
# Metabase TEST credentials
# -----------------------------
TEST_METABASE_CONTAINER="metabase_demo"
TEST_POSTGRES_CONTAINER="metabase_pg_demo"
TEST_DB_NAME="metabase"
TEST_DB_USER="metabase"
TEST_DB_PASS="metabase"
TEST_DB_HOST="db"
TEST_DB_PORT="5432"

# -----------------------------
# Backup options
# -----------------------------
BACKUP_DIR="./metabase_backups"
COPY_TO_TEST=false          # true / false
TEST_HOST="TEST.server.ip"   # required if COPY_TO_TEST=true
TEST_USER="TESTuser"         # required if COPY_TO_TEST=true
TEST_PATH="/tmp"             # target path on TEST server
