{
 "title": "data_platform",
 "tags": [ "data_platform" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Success DAG ETL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_run_status{dag_id=\"etl_csv_pipeline\", state=\"success\"}"
    }
   ]
  },
  {
   "title": "Failed DAG ETL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_run_status{dag_id=\"etl_csv_pipeline\", state=\"failed\"}"
    }
   ]
  },
  {
   "title": "ETL DAG Average Duration (seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "airflow_dag_run_duration_seconds_sum{dag_id=\"etl_csv_pipeline\"} / airflow_dag_run_duration_seconds_count{dag_id=\"etl_csv_pipeline\"}"
    }
   ]
  },
  {
   "title": "Airflow Task Success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "airflow_task_status{dag_id=\"etl_csv_pipeline\", state=\"success\"}"
    }
   ]
  },
  {
   "title": "Airflow Task Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "airflow_task_status{dag_id=\"etl_csv_pipeline\", state=\"failed\"}"
    }
   ]
  },
  {
   "title": "Airflow Task Upstream Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "airflow_task_status{dag_id=\"etl_csv_pipeline\", state=\"upstream_failed\"}"
    }
   ]
  },
  {
   "title": "Airflow Process CPU (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"airflow-exporter:9112\", job=\"airflow\"}"
    }
   ]
  },
  {
   "title": "Airflow Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"airflow-exporter:9112\", job=\"airflow\"}"
    }
   ]
  },
  {
   "title": "Python GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "python_gc_collections_total{instance=\"airflow-exporter:9112\", job=\"airflow\"}"
    }
   ]
  },
  {
   "title": "Python GC Uncollectable Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{instance=\"airflow-exporter:9112\", job=\"airflow\"}"
    }
   ]
  },
  {
   "title": "Minio Up Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "up{instance=\"minio:9000\", job=\"minio\"}"
    }
   ]
  },
  {
   "title": "Minio CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{instance=\"minio:9000\", job=\"minio\"}[1m])"
    }
   ]
  },
  {
   "title": "PostgreSQL Up Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "up{job=\"postgres\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"airflow\", state=\"active\"}",
     "legendFormat": "Active (Airflow)"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"airflow\", state=\"idle\"}",
     "legendFormat": "Idle (Airflow)"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"airflow\", state=\"idle in transaction\"}",
     "legendFormat": "Idle in transaction (Airflow)"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\", state=\"active\"}",
     "legendFormat": "Active (Postgres)"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\", state=\"idle\"}",
     "legendFormat": "Idle (Postgres)"
    },
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\", state=\"idle in transaction\"}",
     "legendFormat": "Idle in transaction (Postgres)"
    }
   ]
  }
 ]
}