{
 "title": "Ingestion Dashboard",
 "tags": [
  "minio",
  "airflow",
  "postgres",
  "ingestion"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Airflow DAG Avg Duration (sec)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_run_duration_seconds_sum / airflow_dag_run_duration_seconds_count"
    }
   ]
  },
  {
   "title": "MinIO Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_s3_traffic_received_bytes[1m])",
     "legendFormat": "Incoming Bytes"
    },
    {
     "expr": "rate(minio_s3_traffic_sent_bytes[1m])",
     "legendFormat": "Outgoing Bytes"
    }
   ]
  },
  {
   "title": "Postgres I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend_total[1m])",
     "legendFormat": "Backend Buffers Written"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total[1m])",
     "legendFormat": "Checkpoint Buffers Written"
    }
   ]
  }
 ]
}