{
 "title": "01-Platform Monitoring Overview",
 "tags": [
  "data lake",
  "postgreSQL",
  "airflow",
  "minio",
  "spark",
  "metabase",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/minio_data_lake_dashboard/data-lake-health\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Data Lake Dashboard\n  </a>\n</div>\n"
   }
  },
  {
   "title": "MinIO Up",
   "type": "stat",
   "description": "Real-time health status of the MinIO cluster. Green indicates all nodes are operational, red indicates cluster issues.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minio_cluster_health_status" }
   ]
  },
  {
   "title": "MinIO Uptime ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(minio_cluster_health_status[24h])* 15"
    }
   ]
  },
  {
   "title": "MinIO CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds[1m]) * 100"
    }
   ]
  },
  {
   "title": "MinIO RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes",
     "legendFormat": "Ram usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/metabase-monitoring/metabase-monitoring\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Metabase dashboard\n  </a>\n</div>\n"
   }
  },
  {
   "title": "Metabase Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metabase_up" }
   ]
  },
  {
   "title": "Metabase Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(metabase_up[24h]) * 15\r\n"
    }
   ]
  },
  {
   "title": "Metabase CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metabase_cpu_percent" }
   ]
  },
  {
   "title": "Metabase RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "metabase_memory_mb\r\n", "legendFormat": "Ram usage" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/postgres-monitoring-v1/postgresql-monitoring\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Postgres dashboard\n  </a>\n</div>\n"
   }
  },
  {
   "title": "PostgreSQL Up",
   "type": "stat",
   "description": "Indicates if PostgreSQL is online and responding to queries",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "PostgreSQL Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pg_up[24h]) * 15\r\n"
    }
   ]
  },
  {
   "title": "PostgreSQL CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pg_settings_cpu_operator_cost)"
    }
   ]
  },
  {
   "title": "PostgreSQL RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "Ram usage" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/a23a7e6f-3feb-45f4-902e-95dfbcec13da/airflow-monitoring-dashboard\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Airflow dashboard\n  </a>\n</div>\n\n\n\n"
   }
  },
  {
   "title": "Airflow Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_up{job=\"airflow-global\"}"
    }
   ]
  },
  {
   "title": "Airflow Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  airflow_up{job=\"airflow-global\", instance=\"airflow-exporter:9112\"}[24h]\r\n) * 15\r\n"
    }
   ]
  },
  {
   "title": "Airflow CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_ram_usage_mb{job=\"airflow-global\"}"
    }
   ]
  },
  {
   "title": "Airflow RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "airflow_cpu_usage_percent{job=\"airflow-global\"}",
     "legendFormat": "Ram usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/spark-monitoring/spark-cluster-monitoring\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Spark dashboard\n  </a>\n</div>\n\n\n"
   }
  },
  {
   "title": "Spark Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spark_exporter_up" }
   ]
  },
  {
   "title": "Spark Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(spark_exporter_up[24h]) *15"
    }
   ]
  },
  {
   "title": "Spark CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(spark_cores_used / spark_cores_total) * 100"
    }
   ]
  },
  {
   "title": "Spark RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(spark_memory_used_mb / spark_memory_total_mb) * 100",
     "legendFormat": "Ram usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <a href=\"http://grafana.itceq.tn/d/marquez-simple-stats/07-marquez-jobs-and-datasets?orgId=1&refresh=10s\"\n     target=\"_blank\"\n     style=\"font-size:24px; font-weight:bold; color:#3274D9; text-decoration:none;\">\n    Marquez dashboard\n  </a>\n</div>\n\n\n"
   }
  },
  {
   "title": "Marquez Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"marquez-jmx\"}"
    }
   ]
  },
  {
   "title": "Marquez Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{job=\"marquez-jmx\"}[24h]) *15"
    }
   ]
  },
  {
   "title": "Marquez CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100"
    }
   ]
  },
  {
   "title": "Marquez RAM Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"marquez-http\"}",
     "legendFormat": "Ram usage"
    }
   ]
  }
 ]
}