#   le plus important, il connecte Trino à MinIO via Hive
connector.name=hive
# L'URI reste le même (port standard Thrift)
hive.metastore.uri=thrift://hive-metastore:9083 
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=minio
hive.s3.aws-secret-key=minio123
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.allow-add-column=true
# Important pour éviter les erreurs de timeout sur les gros fichiers
hive.s3.socket-timeout=5m
hive.metastore.uri=thrift://hive-metastore:9083
