#Written by CorePropertiesLocator
#Tue Nov 25 13:08:46 UTC 2025
numShards=1
collection.configName=fulltext_index
name=fulltext_index_shard1_replica_n1
replicaType=NRT
shard=shard1
collection=fulltext_index
coreNodeName=core_node2
