events {}
http {
    server {
        listen 80;
        # 1. Route API calls to the Marquez Backend
        location /api/v1 {
            proxy_pass http://marquez:5000;
        }
        # 2. Route everything else to the Marquez UI
        location / {
            proxy_pass http://marquez-web:3000;
        }
    }
}