global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow-global'
    metrics_path: /airflow_metrics
    static_configs:
      - targets: ['airflow-exporter:9112']
    scrape_interval: 60s
    scrape_timeout: 50s

  - job_name: 'airflow-errors'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-exporter:9112']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'spark-master-jmx'
    metrics_path: /metrics
    static_configs:
      - targets: ['spark-master:8090']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-worker-jmx'
    metrics_path: /metrics
    static_configs:
      - targets: ['spark-worker:8091']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-master-app'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-master:8080']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-worker-app'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-worker:8081']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-api-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['spark-exporter:9091']
    scrape_interval: 15s
    scrape_timeout: 10s




