global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow-global'
    metrics_path: /airflow_metrics
    static_configs:
      - targets: ['airflow-exporter:9112']
    scrape_interval: 60s
    scrape_timeout: 50s

  - job_name: 'airflow-errors'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-exporter:9112']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'spark-master'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-master:8080']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-worker'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-worker:8081']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'spark-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['spark-exporter:9091']
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'metabase'
    metrics_path: /metrics
    static_configs:
      - targets: ['metabase-exporter:9101']
    scrape_interval: 30s
    scrape_timeout: 25s
    
# Marquez via JMX Exporter
  - job_name: 'marquez-jmx'
    metrics_path: /metrics
    static_configs:
      - targets: ['marquez:9404']
    scrape_interval: 30s
    scrape_timeout: 25s

  - job_name: 'marquez-http'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['marquez:5000'] 

  - job_name: 'sql-exporter'
    static_configs:
      - targets: ['sql-exporter:9399']